# - hosts: all

- hosts: pi4
  vars_files: variables/all.yml
  roles:
    - traefik_authelia
    - ovpn_qbit
    - wireguard
    - audioserve
    - ytdl

- hosts: pi3
  vars_files: variables/all.yml
  - roles
    - influx_grafana
    - homer
    - pihole
    - trilium
    - mqtt_telegraf
