---
- name: Audioserve

  docker_compose:
    project_name: nansi_audioserve
    pull: yes

    definition:
      version: '3.4'

      networks:
        traefik:
          external:
            name: traefik

      services:
        audioserve:
          image: cottoneyedbro/audioserve:latest
          container_name: nansi_audioserve
          volumes:
            - '{{ dir.storage }}/music:/music'
            - '{{ dir.storage }}/audiobooks:/audiobooks'
          environment:
            PORT: 3000
            AUDIOSERVE_SHARED_SECRET: '{{ audioserve.secret }}'
          restart: unless-stopped
          networks:
            - traefik
          labels:
            - traefik.enable=true
            - traefik.http.routers.books.tls.certresolver=tmp
            - traefik.http.routers.books.rule=Host(`books.{{ tld.home }}`)
            - traefik.http.routers.books.middlewares=authelia@docker
            - traefik.http.routers.books.service=books
            - traefik.http.services.books.loadbalancer.server.port=3000
          command:
            - '/audiobooks'
            - '/music'
            - '--t-cache-disable'
