---

- name: cp ovpn auth | template
  template:
    src: vpn.auth
    dest: '{{ dir.docker }}/ovpn/'

- name: Ensure qbit dir exists | file
  file: path={{ dir.docker }}/qbittorrent state=directory

- name: cp qBit config | template
  template:
    src: qBittorrent.conf
    dest: '{{ dir.docker }}/qbittorrent/'

- name: OpenVpn & qBittorrent

  docker_compose:
    project_name: nansi_openvpn_qbit
    pull: yes

    definition:
      version: '3.4'

      volumes:
        qbit_config:
          driver: local

      services:
        vpn:
          image: derkades/ovpn-client:latest
          container_name: nansi_vpn
          ports:
            - 8080:8080
            - 6881:6881
            - 6881:6881/udp
          volumes:
            - '{{ dir.docker }}/openvpn/node-ch-05.protonvpn.net.udp.ovpn:/client.ovpn'
            - '{{ dir.docker }}/openvpn/vpn.auth:/vpn.auth'
          dns:
            - '1.1.1.1'
            - '8.8.8.8'
          cap_add:
            - NET_ADMIN
          devices:
            - /dev/net/tun:/dev/net/tun
          environment:
            LOCAL_NETWORK: '{{ cidr.lan }}'

        qbit:
          image: linuxserver/qbittorrent:latest
          container_name: nansi_qbit
          environment:
            - PGID=1000
            - PUID=1000
          depends_on:
            - vpn
          restart: unless-stopped
          network_mode: service:vpn
          volumes:
            - '{{ dir.storage }}/downloads:/downloads'
            - '{{ dir.storage }}:/storage'
            - '{{ dir.docker }}/qbittorrent/qBittorrent.conf:/config/qBittorrent.conf'
