---
- name: Audiobookshelf

  docker_compose:
    project_name: nansi_audiobookshelf
    pull: yes

    definition:
      version: '3.4'

      networks:
        traefik:
          external:
            name: traefik

      services:
        audiobookshelf:
          image: advplyr/audiobookshelf:latest
          container_name: nansi_audiobookshelf
          volumes:
            - '{{ dir.storage }}/audiobooks:/audiobooks'
            - audiobookshelf-metadata:/metadata
            - audiobookshelf-config:/config
          networks:
            - traefik
          labels:
            - traefik.enable=true
            - traefik.http.routers.audiobookshelf.tls.certresolver=tmp
            - traefik.http.routers.audiobookshelf.rule=Host(`audiobookshelf.{{ tld.home }}`)
            - traefik.http.routers.audiobookshelf.middlewares=authelia@docker
            - traefik.http.routers.audiobookshelf.service=audiobookshelf
            - traefik.http.services.audiobookshelf.loadbalancer.server.port=80
            - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https # enable websockets, possibly

      volumes:
        audiobookshelf-metadata:
          driver: local
        audiobookshelf-config:
          driver: local
