###############################################################
#                   Authelia configuration                    #
###############################################################

server:
  host: 0.0.0.0
  port: 9091

log.level: error

jwt_secret: {{ authelia.jwt_secret }}

default_redirection_url: https://www.{{ tld.base }}

totp:
  issuer: authelia.com
  period: 30
  skew: 1

authentication_backend:
  disable_reset_password: true
  file:
    path: /config/users_database.yml
    password:
      algorithm: sha512 # argon2id
      iterations: 1000
      salt_length: 16

access_control:
  default_policy: deny
  rules:
    - domain: "authelia.{{ tld.home }}"
      policy: bypass

    - domain:
      - "qbit.{{ tld.home }}"
      - "dashboard.{{ tld.home }}"
      - "trilium.{{ tld.home }}"
      policy: two_factor
      subject:
      - ["group:admin", "group:super-admin"]

    - domain: "recipe.{{ tld.home }}"
      policy: two_factor
      subject:
      - ["group:user"]

    - domain: "*.{{ tld.home }}"
      policy: two_factor
      subject:
      - ["group:admin", "group:super-admin"]

    - domain: "{{ tld.home }}"
      policy: two_factor
      subject:
      - ["group:admin", "group:super-admin"]

session:
  name: authelia_session
  secret: {{ authelia.session_secret }}
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
  domain: {{ tld.home }}

regulation:
  max_retries: 3
  find_time: 1h # can't be larger than ban_time
  ban_time: 1h

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt

theme: grey
