[http.routers]
  [http.routers.trilium]
    rule = "Host(`trilium.{{ tld.home }}`)"
    entrypoints = ["websecure"]
    service = "trilium"
    middlewares = ["authelia@docker"]
  [http.routers.trilium.tls]
    certResolver = "tmp"

[http.services]
  [http.services.trilium.loadBalancer]
    [[http.services.trilium.loadBalancer.servers]]
      url = "http://{{ host.pi3.ip }}:22222"
