---
- name: ytdl

  docker_compose:
    project_name: nansi_metube
    pull: yes

    definition:
      version: '3.4'

      networks:
        traefik:
          external:
            name: traefik

      services:
        metube:
          image: alexta69/metube:latest
          container_name: nansi_metube
          restart: unless-stopped
          environment:
            - PUID=1000
            - GUID=1000
            - AUDIO_DOWNLOAD_DIR=/downloads/audio
            - TZ={{ tz }}
          networks:
            - traefik
          volumes:
            - "{{ dir.storage }}/ytdl:/downloads"
          labels:
            - traefik.enable=true
            - traefik.http.routers.ytdl.tls.certresolver=tmp
            - traefik.http.routers.ytdl.rule=Host(`ytdl.{{ tld.home }}`)
            - traefik.http.routers.ytdl.middlewares=authelia@docker
            - traefik.http.routers.ytdl.service=ytdl
            - traefik.http.services.ytdl.loadbalancer.server.port=8081
